title: My awesome title
author: GitHub User skieieies
email: skieieies@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  あのイーハトーヴォの
  すきとおった風、
  夏でも底に冷たさをもつ青いそら、
  うつくしい森で飾られたモリーオ市、
  郊外のぎらぎらひかる草の波。

# social links
twitter_username: skieieies # DO NOT include the @ character, or else the build will fail!
github_username:  skieieies # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
